/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
 * the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

fun main() {
    val series = mutableListOf<Int>()
    var i = 3
    var sum = 2
    series.add(1)
    series.add(2)
    while (series[i-2] < 4000000) {
        val curr = series[i-1-1] + series[i-2-1]
        if (curr % 2 == 0) sum += curr
        series.add(curr)
        i += 1
    }

    println(sum)
}